### ISSUE TITLE
v6版本出现了以下错误

### ISSUE THREAD

**Issue by wemindful** [ZJU-lishuang/yolov5_prune#76]
let's test the original model first:
Traceback (most recent call last):
  File "prune_yolov5s.py", line 43, in <module>
    origin_model_metric = eval_model(model)
  File "prune_yolov5s.py", line 38, in <lambda>
    model=model)
  File "/home/yolov5_prune-6/test.py", line 151, in test
    data = parse_data_cfg(data)
  File "/home/yolov5_prune-6/utils/parse_config.py", line 39, in parse_data_cfg
    key, val = line.split('=')
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by wemindful** [comment]
RuntimeError: shape '[4, 3, 6, 12, 64]' is invalid for input of size 589824
